#!/bin/sh
#
# Copyright (C) 2022 Patricio Moracho
#
# zonap is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# Filename    : zonap
# Description : scraping data from zonaprop
# Require     : xsel, xclip, scrapper

url=`xsel -ob`

scrap() {
    echo "scraping $url"
    scrapper zonaprop -t csv -b -q -p "$url" | xclip -selection cliboard
}

scrap
